# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85fa272cf3a65c95f518cf0adef53e416cda29d265a75964371d8c08cf0b81fc8f0055fc6f464855444c8ff052c644064b3df0ccb6998d8c55fc811df40f2e58

test:
  secret_key_base: e15f8db13dc0c0a2f609b5b07a00b24ea8abbb45f7b20170cf3d42a810c4b3aa05ea26692b92e76b6ec29844da4ed6c277de9786a532410b25a85c1bcb07c47f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
